# Generated by Django 4.2 on 2024-02-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(to='example.language'),
        ),
    ]
