# Generated by Django 4.2 on 2024-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_programmer_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='creator',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='programmer',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
