# Generated by Django 4.2 on 2024-02-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_company_location_language_creator_language_paradigm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
