# Generated by Django 4.2 on 2024-02-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_programmer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
