# Generated by Django 4.2 on 2024-02-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlexample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='company',
            new_name='course',
        ),
    ]
